# Generated by Django 4.2.5 on 2024-02-05 09:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("speciality", models.CharField(max_length=60)),
                ("qualification", models.CharField(max_length=30)),
                ("profile", models.ImageField(upload_to="profile/")),
                ("address", models.TextField()),
                ("contact", models.CharField(max_length=10)),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
    ]
