# Generated by Django 4.2.5 on 2024-02-26 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_feedback"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(default="", max_length=30)),
                ("email", models.EmailField(max_length=254)),
                ("address", models.TextField(default="")),
                ("city", models.CharField(default="", max_length=10)),
                ("name_on_card", models.CharField(default="", max_length=30)),
                ("credit_card_number", models.IntegerField()),
                ("exp_month", models.CharField(default="", max_length=10)),
                ("state", models.CharField(default="", max_length=30)),
                ("zip_code", models.IntegerField()),
                ("exp_year", models.IntegerField()),
                ("cvv", models.IntegerField()),
            ],
        ),
    ]
